// src/components/ProjectCard.vue
<!-- src/components/ProjectCard.vue -->
<template>
  <div
    class="rounded-lg bg-white text-dark border-gray-200 shadow-sm flex flex-col overflow-hidden border hover:shadow-lg transition-all duration-300 ease-out h-full">
    <a :href="projectHref">
      <img :src="imageSrc" :alt="imageAlt" class="w-full h-full" />
    </a>
    <div class="flex flex-col space-y-1.5 p-6 px-3">
      <h3 class="font-semibold tracking-tight mt-1 text-base">{{ title }}</h3>
      <time class="font-sans text-xs">{{ period }}</time>
      <p class="prose max-w-full text-pretty font-sans text-xs text-neutral-500 dark:prose-invert">{{ description }}</p>
    </div>
    <div class="p-6 pt-0 mt-auto flex flex-col px-2">
      <div class="mt-2 flex flex-wrap gap-1 gap-y-2">
        <TechnoItem v-for="tech in technologies" :key="tech" :techno="tech" />
      </div>
    </div>
    <div class="flex items-center p-6 pt-0 px-2 pb-2 gap-1">
      <SocialLinkButton v-for="link in socialLinks" :key="link.text" :href="link.href" :text="link.text"/>
    </div>
  </div>
</template>

<script setup lang="ts">
import TechnoItem from './TechnoItem.vue';
import SocialLinkButton from './SocialLinkButton.vue';
import { PropType } from 'vue';

defineProps({
  title: {
    type: String,
    required: true,
  },
  period: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  imageSrc: {
    type: String,
    required: true,
  },
  imageAlt: {
    type: String,
    required: true,
  },
  projectHref: {
    type: String,
    required: true,
  },
  technologies: {
    type: Array as PropType<string[]>,
    required: true,
  },
  socialLinks: {
    type: Array as PropType<Array<{ href: string; text: string; }>>,
    required: true,
  },
});
</script>

<style scoped></style>

// app/components/ProjectCard.tsx
import Link from "next/link";

interface Project {
  project: {
    title: string;
    stack: string[];
    description: string;
    category: string;
    url: string;
    image: string;
  };
  classNames: string;
}

export default function ProjectCard({ project, classNames }: Project) {
  return (
    <>
      {project.image === "" ? (
        <Link
          href={project.url}
          className="hover:scale-105 transition ease-in-out duration-100 h-95"
        >
          <div
            className={`rounded-lg p-5 h-full flex flex-col items-center justify-center dark:bg-neutral-800 ${classNames}`}
          >
            <h3 className="text-2xl font-semibold">{project.title}</h3>
            <p className="text-xl">{project.description}</p>
          </div>
        </Link>
      ) : (
        <Link
          href={project.url}
          className="hover:scale-105 transition ease-in-out duration-100"
        >
          <div
            style={{
              backgroundImage: `linear-gradient(to top, rgba(0, 0, 0, 1), transparent), url(${project.image})`,
            }}
            className={`rounded-lg p-5 bg-cover ${classNames}`}
          >
            <div className="flex flex-row justify-between items-end h-48">
              <div className="flex flex-col justify-between items-start">
                <h4 className="font-semibold mb-2">
                  <span className="bg-gradient-to-r from-rose-500 to-amber-500 text-transparent bg-clip-text text-xl">
                    {project.category}
                  </span>
                </h4>
                <h3 className="font-semibold text-2xl text-white">{project.title}</h3>
              </div>
            </div>
          </div>
        </Link>
      )}
    </>
  );
}
